### PR TITLE
Bernede1/debug

### PR DESCRIPTION
**Pull request by adrienbernede**
Solves #87 

I recently had the need for a debug option.

### CODE REVIEW

**Comment by cyrush** [comment]
Looks like this adds debug args if there is a spec provided?

Could we make it an orthogonal option (`--spack-debug`)?

**Comment by adrienbernede** [comment]
I don’t know why I had stop half way.
Testing now...

**Comment by adrienbernede** [comment]
Works for me.

**Comment by adrienbernede** [comment]
@chapman39 love the new testing capabilities 👍🏻

**Review by cyrush — APPROVED** [review]
Looks good!

**Review by kennyweiss — APPROVED** [review]
Thanks @adrienbernede 

Please also add a line about this new option to the `RELEASE-NOTES`.

**Pull request merged**
