### PR TITLE
Remove wrong documentation

### PR DESCRIPTION
**Pull request by white238**

### CODE REVIEW

**Comment by cyrush** [comment]
"%clang"" is still used as the default spec on macOS:

https://github.com/LLNL/uberenv/blob/fa5378549518560008ae345bd8a2e7ab01f8cb89/uberenv.py#L516

but yes -- the default config for darwin folder is no longer used.  

Side Note: Not sure why that was removed?

**Comment by white238** [comment]
I'm not sure.  I just noticed when I was grep'ing in Serac for a path I missed moving to a submodule.

**Comment by white238** [comment]
Fixed @cyrush suggestion

**Review by adrienbernede — APPROVED** [review]
LGTM

**Comment by adrienbernede** [comment]
> "%clang"" is still used as the default spec on macOS:
> 
> https://github.com/LLNL/uberenv/blob/fa5378549518560008ae345bd8a2e7ab01f8cb89/uberenv.py#L516
> 
> but yes -- the default config for darwin folder is no longer used.
> 
> Side Note: Not sure why that was removed?

The Uberenv repo never had a `spack_configs` directory, the conduit version did. Or maybe I misunderstood the question?

**Comment by white238** [comment]
> > "%clang"" is still used as the default spec on macOS:
> > https://github.com/LLNL/uberenv/blob/fa5378549518560008ae345bd8a2e7ab01f8cb89/uberenv.py#L516
> > 
> > but yes -- the default config for darwin folder is no longer used.
> > Side Note: Not sure why that was removed?
> 
> The Uberenv repo never had a `spack_configs` directory, the conduit version did. Or maybe I misunderstood the question?

I think uberenv (or at least one version did) defaulted the `spack_config_path` to `spack_configs/darwin` on OSX at some point.

**Comment by cyrush** [comment]
hmm, looking closer -- I think the logic is still there?

https://github.com/LLNL/uberenv/blob/fa5378549518560008ae345bd8a2e7ab01f8cb89/uberenv.py#L568

**Comment by cyrush** [comment]
here is the logic from ancient uberenv for comparison:

https://github.com/LLNL/conduit/blob/83ef572d7750e746ed9319b40cb8dc9126e13d8e/scripts/uberenv/uberenv.py#L170

**Comment by adrienbernede** [comment]
Hmm, so yes, I misunderstood the question ;)

**Comment by cyrush** [comment]
@adrienbernede correct -- sorry, I was referring to using the dir if it exists, not having the dir in the uberenv repo.

**Review by cyrush — APPROVED** [review]

**Pull request merged**
