### PR TITLE
Use `spack bootstrap now` to find clingo

### LINKED ISSUE #118: Move to `spack bootstrap now`
We should move away from installing clingo via pip. This was originally implemented before Spack had the solution it does now. It also sometimes does not find the pip installed clingo even though its very clearly there.

### LINKED ISSUE #134: Eventually remove setting concretizer:clingo
I was building [Spack develop today](https://github.com/spack/spack/commit/b1905186a621d8f2b2afe13921d30fd056b19aeb) and noticed this new warning:

```
[exe: /usr/workspace/meemee/serac/serac_libs1/spack/bin/spack config --scope defaults add config:concretizer:clingo]
==> Warning: Spack supports only clingo as a concretizer from v0.23. The config:concretizer config option is ignored.
```

It's not going to break things if we leave this option, but the warning is printed after every Spack command.

### PR DESCRIPTION
**Pull request by chapman39**
Use spack commands to setup clingo rather than relying on pip.

- [x] make clingo default and only option (Fixes #134)
  - the other concretizer option will be removed in future spack versions and has been removed since v0.23)
- [x] bootstrap clingo (Fixes #118)
- [x] fix `spack_setup_clingo` option, i realized this was always broken.
- [x] update .ci package recipes to `import spack.package` rather than just `spack`, as it's required in recent spack versions

### CODE REVIEW

**Comment by chapman39** [comment]
Should clingo be the default concretizer in uberenv?

**Comment by chapman39** [comment]
```
[exe: /home/runner/work/uberenv/uberenv/.ci/test-project/uberenv_libs/spack/bin/spack bootstrap now]
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_[64](https://github.com/LLNL/uberenv/actions/runs/6030953662/job/16363766980?pr=122#step:4:65)/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spack
==> Installing "clingo-bootstrap@=spack%gcc@=10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-x86_64" from a buildcache
[exe: /home/runner/work/uberenv/uberenv/.ci/test-project/uberenv_libs/spack/bin/spack bootstrap status]
Spack v0.21.0.dev0 - python@3.10

[PASS] Core Functionalities

[PASS] Binary packages
```

https://github.com/LLNL/uberenv/actions/runs/6030953662/job/16363766980?pr=122#step:4:66

**Review by cyrush — APPROVED** [review]
Looks good to me!

**Review by white238 — APPROVED** [review]
Thanks @chapman39 !

**Pull request merged**
