### PR TITLE
Uses `git checkout` instead of `git reset` for `spack_commit` checkout

### LINKED ISSUE #8: Checking out a custom spack branch
When ``spack_commit`` is present in the ``project.json`` file, uberenv uses that commit of spack.

It currently uses ``git reset --hard $commit``, which resets the branch pointer for spack's develop branch to the desired commit.  Unfortunately, this makes it look like it is still using the develop branch, which could be confusing to users.

Instead, it should use ``git checkout $commit``, which puts spack in a detached head state indicating the current commit.

### PR DESCRIPTION
**Pull request by kennyweiss**
Resolves #8.

### CODE REVIEW

**Comment by cyrush** [comment]
checkout can fail in cases where reset will not due to dirty state, i think thats why i have it there

**Comment by kennyweiss** [comment]
Thanks @cyrush.  In this case though, we just cloned a clean spack.  
Are there possible failure cases here?

With this change, it seems much easier (to me) to understand which commit our local spack is based on.

**Comment by cyrush** [comment]
I see this only happens right after clone. I definitely had a reason but the logic may have evolved to note be needed.

**Comment by cyrush** [comment]
Had some time to ponder, i think this is a good improvement. 
I wanted to check the behavior when combined with the uberenv --pull argument. 

pull should not change anything when we use a specific commit. 

I did a quick check using git directly,  from my test I believe we are good

**Comment by cyrush** [comment]
thanks @kennyweiss!

**Pull request merged**
