### PR TITLE
Make clingo install optional

### PR DESCRIPTION
**Pull request by adrienbernede**
Pretty explicit

### CODE REVIEW

**Review by cyrush — APPROVED** [review]

**Review by white238 — APPROVED** [review]

**Comment by white238** [comment]
Can you add a release note about this?

**Comment by adrienbernede** [comment]
@white238 I will, I wasn't expecting reviews to come so quickly.
I'll add documentation for this if there is a place for .uberen-config.json parameters.

**Comment by white238** [comment]
> @white238 I will, I wasn't expecting reviews to come so quickly. I'll add documentation for this if there is a place for .uberen-config.json parameters.

I am trying to be better! But I could slow down if you like....

**Comment by adrienbernede** [comment]
Done!
I did my best to keep up with your pace... ;)

**Comment by white238** [comment]
Thanks @adrienbernede feel free to merge.

**Comment by adrienbernede** [comment]
Will test first.

**Pull request merged**
